apiVersion: v1
kind: Template
labels:
  template: bayesian-gremlin-server
metadata:
  name: bayesian-gremlin-server
  annotations:
    description: bayesian-gremlin-server
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: bayesian-gremlin-${CHANNELIZER}
    name: bayesian-gremlin-${CHANNELIZER}
  spec:
    ports:
    - name: "8182"
      port: 8182
      protocol: TCP
      targetPort: 8182
    selector:
      service: bayesian-gremlin-${CHANNELIZER}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-gremlin-${CHANNELIZER}
    name: bayesian-gremlin-${CHANNELIZER}
  spec:
    replicas: 1
    selector:
      service: bayesian-gremlin-${CHANNELIZER}
    template:
      metadata:
        labels:
          service: bayesian-gremlin-${CHANNELIZER}
      spec:
        containers:
        - env:
          - name: REST
            value: ${REST_VALUE}
          - name: DYNAMODB_CLIENT_ENDPOINT
            value: ${DYNAMODB_CLIENT_ENDPOINT}
          - name: DYNAMODB_PREFIX
            valueFrom:
               configMapKeyRef:
                 name: bayesian-config
                 key: dynamodb-prefix
          - name: DYNAMODB_CLIENT_CREDENTIALS_CLASS_NAME
            value: ${DYNAMODB_CLIENT_CREDENTIALS_CLASS_NAME}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws
                key: dynamodb-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws
                key: dynamodb-secret-access-key
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          imagePullPolicy: Always
          name: bayesian-gremlin
          ports:
          - containerPort: 8182
            protocol: TCP
          resources:
            requests:
              memory: ${MEMORY_REQUEST}
            limits:
              memory: ${MEMORY_LIMIT}
          readinessProbe:
            httpGet:
              # let's query non-existing data so we get response immediately
              path: /?gremlin=g.V().has('vertex_label','foobar').count()
              port: 8182
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              # let's query non-existing data so we get response immediately
              path: /?gremlin=g.V().has('vertex_label','foobar').count()
              port: 8182
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
parameters:
- description: Value of the 'storage.dynamodb.client.credentials.class-name' property in dynamodb.properties
  name: DYNAMODB_CLIENT_CREDENTIALS_CLASS_NAME
  required: true
  value: "com.amazonaws.auth.DefaultAWSCredentialsProviderChain"
- description: Value of the 'storage.dynamodb.client.endpoint' property in dynamodb.properties
  name: DYNAMODB_CLIENT_ENDPOINT
  required: false
  value: "https://dynamodb.us-east-1.amazonaws.com"
- description: Change the channelizer being used to deploy the gremlin server. Set this to "1" for HTTP channelizer, and "0" for WebSocket channelizer. Defaults to "0" i.e. WebSocket.
  name: REST_VALUE
  value: "0"
- description: MEMORY_LIMIT
  name: MEMORY_LIMIT
  required: true
  value: "1536Mi"
- description: MEMORY_REQUEST
  name: MEMORY_REQUEST
  required: true
  value: "1536Mi"
- description: Name of the channelizer being used. Setting this will not change the channelizer, this will merely influence the names of OpenShift objects being created. To change the channelizer, see REST_VALUE.
  name: CHANNELIZER
  required: true
  value: ws

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.centos.org"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "datamodel/gremlin"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "1.1.0"
